name: Auto Pull
on:  [push]
jobs:
  build:
    name:  Build
    runs-on:  ubuntu-latest
    steps:
    - name:  execute remote pull
      uses:  appleboy/ssh-action@master
      with:
        host:  ${{secrets.IP}}
        username:  ${{secrets.USERNAME}}
        password:  ${{secrets.PASSWORD}}
        port:  ${{secrets.PORT}}
        script:
          cd /root/bbbe
          git pull origin dev
